//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP8.BluetoothChiFouMi.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP8.BluetoothChiFouMi.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bluetooth Chi-Fou-Mi.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer.
        /// </summary>
        public static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion à l&apos;appareil sélectionné.
        /// </summary>
        public static string ConnectButtonCaption {
            get {
                return ResourceManager.GetString("ConnectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bluetooth n&apos;est pas activé..
        /// </summary>
        public static string Err_BluetoothOff {
            get {
                return ResourceManager.GetString("Err_BluetoothOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bluetooth Off.
        /// </summary>
        public static string Err_BluetoothOffCaption {
            get {
                return ResourceManager.GetString("Err_BluetoothOffCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To run this app, you must have ID_CAP_PROXIMITY enabled in WMAppManifest.xaml.
        /// </summary>
        public static string Err_MissingCaps {
            get {
                return ResourceManager.GetString("Err_MissingCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de se Connecter.
        /// </summary>
        public static string Err_NoConnectTitle {
            get {
                return ResourceManager.GetString("Err_NoConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;adversaire sélectionné dans la liste !.
        /// </summary>
        public static string Err_NoPeer {
            get {
                return ResourceManager.GetString("Err_NoPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes connecté..
        /// </summary>
        public static string Err_NoPeerConnected {
            get {
                return ResourceManager.GetString("Err_NoPeerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are currently not advertising yourself, i.e., a call to PeerFinder.Start() must proceed FindAllPeersAsync().
        /// </summary>
        public static string Err_NotAdvertising {
            get {
                return ResourceManager.GetString("Err_NotAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche Appareils ....
        /// </summary>
        public static string FindButtonCaption {
            get {
                return ResourceManager.GetString("FindButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chi-Fou-Mi.
        /// </summary>
        public static string GamePageName {
            get {
                return ResourceManager.GetString("GamePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une Partie Avec {0} ?.
        /// </summary>
        public static string Msg_ConnectionPrompt {
            get {
                return ResourceManager.GetString("Msg_ConnectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invitation à Jouer.
        /// </summary>
        public static string Msg_ConnectionPromptTitle {
            get {
                return ResourceManager.GetString("Msg_ConnectionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adversaires: {0}..
        /// </summary>
        public static string Msg_FoundPeers {
            get {
                return ResourceManager.GetString("Msg_FoundPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;Adversaire..
        /// </summary>
        public static string Msg_NoPeers {
            get {
                return ResourceManager.GetString("Msg_NoPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scores.
        /// </summary>
        public static string RecordsPageName {
            get {
                return ResourceManager.GetString("RecordsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche d&apos;appareils.
        /// </summary>
        public static string ResearchPeers {
            get {
                return ResourceManager.GetString("ResearchPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fr-FR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo.
        /// </summary>
        public static string UserPseudoText {
            get {
                return ResourceManager.GetString("UserPseudoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string WelcomePageName {
            get {
                return ResourceManager.GetString("WelcomePageName", resourceCulture);
            }
        }
    }
}
